blog/urls.py
from django.urls import path
from . import views
from django.views.generic import ListView

urlpatterns = [
    # Blog list view
    path('', views.PostListView.as_view(), name='blog'),      #----------------------- Generic view controller | Method_1

    # User post view
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),

    # Post detail view
    path('post/<int:pk>/', views.PostDetailView, name='post'),       #----------------------- Normal view controller + Comment Form

    # Create new post
    path('post/new/', views.create_post, name='new_post'),    #----------------------- Normal view controller

    # Edit post
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update_post'),

    # Delete post
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='dele_post'),
    # url(r'^user/(?P<pk>\d+)/$', UserDetailView.as_view(), name="user_view"),  #------- user detail
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myhome.urls')),
    path('blog/', include('blog.urls')),
]

handler404 = 'myhome.views.error'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django import forms
from django.contrib.auth import get_user_model

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE, related_name='blog_post')
    # author = models.ForeignKey(get_user_model(), default=1, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to = "images/")
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return 'id: ' + str(self.id) + ' title: ' + self.title + '\n'
        # return self.title
    def get_absolute_url(self):
        return reverse('post', args=[str(self.pk)])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return 'author: ' + self.author + ' comment: ' + self.body
    
    def get_absolute_url(self):
        return reverse('post', args=[str(self.id)])

blog/forms.py
from django import forms
from .models import Comment, Post
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        self.post = kwargs.pop('post', None)
        super().__init__(*args, **kwargs)

    def save(self, commit = True):
        comment = super().save(commit=False)
        comment.author = self.author
        comment.post = self.post
        comment.save()
    
    class Meta:
        model = Comment
        fields = ["body"]

class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['author'].queryset = User.objects.filter(pk=user.pk)
        
    class Meta:
        model = Post
        fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.http import Http404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, edit
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.
class PostListView(ListView):           #------------------------------ class-base view | Method_1
    queryset = Post.objects.all().order_by('-date')
    template_name = 'blogs/blog.html'
    context_object_name = 'Posts'
    paginate_by = 5

class UserPostListView(ListView):       #------------------------------ class-base view | Method_1
    model = Post
    template_name = 'blogs/user_posts.html'
    context_object_name = 'Posts'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date')

# Post detail
def PostDetailView(request, pk):        #------------------------------ function-base view + comment form
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES, author=request.user, post=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path)
    else:
        form = CommentForm()
    return render(request, 'blogs/post.html', {'post': post, 'form':form})

# Create/new post 
@login_required
def create_post(request):
    if request.method == 'GET':
        context = {'form': PostForm(user=request.user, initial={'author': request.user})}
        return render(request, 'blogs/new_post.html', context)
    elif request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            messages.success(
                request, 'The post has been created successfully.')
            return redirect('blog')
        else:
            messages.error(request, 'Please correct the following errors:')
            return render(request, 'blogs/new_post.html', {'form': form})

# Edit/update post
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Post
    fields = '__all__'
    template_name = 'blogs/update_post.html'
    context_object_name = 'PostUpdate'
    success_message = 'The post has been updated successfully.'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

# Dele post
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Post
    fields = '__all__'
    template_name = 'blogs/dele_post.html'
    context_object_name = 'PostDelete'
    success_url = '/blog/'
    success_message = 'The post has just been deleted.'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

blog/templates/blogs/blog.html
{% extends 'pages/base.html' %}

{% block title %}
    My Blog
{% endblock %}

{% block content %}
    <!-- <a class="mr-2" href="#">{{ post.author }}</a> -->
    <!-- {{post.date|date:"d-m-Y"}} -->
    {% for post in Posts %}
        <article class="media content-section">
            <div class="article-metadata">
            <small class="text-muted">{{ post.date }}</small> 
            </div>
            <div class="blog-img">
                <h2><a class="article-title" href="/blog/{{post.id}}">{{ post.title }}</a></h2>
                {% if post.image %}
                    <img src="{{ post.image.url }}" width="100px" height="auto" style="margin-left: 20px;">
                {% endif %}
            </div>
        </article>
    {% endfor %}
    <hr>
    {% if page_obj.has_next %}
        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next Page</a>
    {% endif %}
{% endblock %}

blog/templates/blogs/dele_post.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}
    Delete Post
{% endblock title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p class="alert alert-info">Are you sure to delete "{{ object.title }}" </p>
        <input class="btn pag-btn" type="submit" value="Comfirm"/>
    </form>
    <form action="/blog/post/{{object.id}}">
        <input class="btn pag-btn" type="submit" value="Cancel"/>
    </form>
{% endblock content %}

blog/templates/blogs/new_post.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}
    New Post
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}  
        <div class="form-new">
            <ul style="list-style: none;">
                <li class="flex-container">
                    <p>{{form.title.label}}</p>
                    {{form.title}}
                </li>

                <li class="flex-container">
                    <p>{{form.author.label}}</p>
                    {{form.author}}
                </li>

                <!-- <script>
                    $('#id_author').attr('disabled', 'disabled');
                </script> -->

                <li class="flex-container">
                    <p>{{form.body.label}}</p>
                    {{form.body}}
                </li>

                <li class="flex-container">
                    <p>{{form.image.label}}</p>
                    {{form.image}}
                </li>
            </ul>
        </div>
        <input class="btn" type="submit" value="Create Post"/>
    </form>
{% endblock content %}

blog/templates/blogs/newpost.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}
    New Post
{% endblock title %}

{% block content %}
    {% csrf_token %}
    {{ form.as_p }}
{% endblock content %}

blog/templates/blogs/post.html
{% extends 'pages/base.html' %}

{% block title %}
    {{post.title}}
{% endblock %}

{% block content %}
    <p style="font-size: small;">{{post.date|date:"d-m-Y"}}</p>
    <center><h3>{{post.title}}</h3></center>

    <!-- auther -->
    <img class="rounded_circle" src="{{ post.author.profile.image.url }}">
    <a href="{% url 'user_posts' post.author.username %}">{{ post.author.profile.user }}</a>
    <h6>on {{post.date}} </h6>
    {% if post.image %}
        <img src="{{ post.image.url }}" width="500px" height="auto">
    {% endif %}
    <p class="article-content">{{post.body|safe|linebreaks}}</p>

    <!-- update post  -->
    {% if post.author == user %}
        <a href="{% url 'update_post' post.pk %}">+ Update This Post</a>

        <!-- delete post  -->
        <a href="{% url 'dele_post' post.pk %}">+ Delete This Post</a>
    {% endif %}
    <hr>

    <!-- display comment  -->
    <p class="comment"><label>Comment:</label></p>
    {% if post.comments.all %}
        {% for comment in post.comments.all %}
            <h4><strong>{{comment.author}}</strong></h4>
            <h6><p>{{comment.date}}</p></h6>
            <p>{{comment.body|linebreaks}}</p>
        {% endfor %}

        <!-- comment those post  -->
        {% if user.username %}
            <form action="{% url 'post' post.id %}" method="POST">
                {% csrf_token %}
                {{form.body}}
                <br>
                <input class="btn pag-btn" type="submit" value="Bình luận"/>
            </form>
        {% else %}
            <p><a href="{% url 'login' %}">Login</a> to post a comment</p>
        {% endif %}
    {% else %}
        {% if user.username %}
            <form action="{% url 'post' post.id %}" method="POST">
                {% csrf_token %}
                <p>Be the first to comment</p>
                {{form.body}}
                <br>
                <input class="btn pag-btn" type="submit" value="Bình luận"/>
            </form>
        {% else %}
            <p><a href="{% url 'login' %}">Login</a> to post the first comment</p>
        {% endif %}
    {% endif %}
{% endblock content %}

blog/templates/blogs/update_post.html
{% extends 'pages/base.html' %}
{% load static %}

{% block title %}
    Update Post
{% endblock title %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}  
    <div class="form-new">
        <ul style="list-style: none;">
            <li class="flex-container">
                <p>{{form.title.label}}</p>
                {{form.title}}
            </li>

            <li class="flex-container">
                <p>{{form.author.label}}</p>
                {{form.author}}
            </li>

            <!-- <script>
                $('#id_author').attr('disabled', 'disabled');
            </script> -->

            <li class="flex-container">
                <p>{{form.body.label}}</p>
                {{form.body}}
            </li>

            <li class="flex-container">
                <p>{{form.image.label}}</p>
                {{form.image}}
            </li>
        </ul>
    </div>
    <input class="btn" type="submit" value="Update"/>
</form>
{% endblock content %}

blog/templates/blogs/user_posts.html
{% extends 'pages/base.html' %}

{% block title %}
    My Post
{% endblock %}

{% block content %}
    <!-- <a class="mr-2" href="#">{{ post.author }}</a> -->
    <!-- {{post.date|date:"d-m-Y"}} -->
    <h1>Posts by <span class="author">{{ view.kwargs.username }}</span> ({{page_obj.paginator.count}})</h1>
    
    {% for post in Posts %}
        <article class="media content-section">
            <div class="article-metadata">
            <small class="text-muted">
                {{ post.date }}
                <div>
                    by
                    <span class="author"> {{ post.author }}</span>
                </div>
            </small> 
            </div>
            <div class="blog-img">
                <h2><a class="article-title" href="/blog/post/{{post.pk}}">{{ post.title }}</a></h2>
                {% if post.image %}
                    <img src="{{ post.image.url }}" width="100px" height="auto" style="margin-left: 20px;">
                {% endif %}
            </div>
        </article>
    {% endfor %}
    <hr>

    <div class="flex-container paginator">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4 pag-btn" href="{{ request.path }}?page=1">First Page</a>
            <a class="btn btn-outline-info mb-4 pag-btn" href="{{ request.path }}?page={{page_obj.previous_page_number}}">Previous Page</a>
        {% endif %}

        <div>
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4 paginfo-btn" href="{{ request.path }}?page={{num}}">{{num}}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-info mb-4 paginfo-btn" href="{{ request.path }}?page={{num}}">{{num}}</a>
                {% endif %}
            {% endfor %}
        </div>

        {% if page_obj.has_next %}
            <div>
                <a class="btn btn-outline-info mb-4 pag-btn" href="{{ request.path }}?page={{page_obj.next_page_number}}">Next Page</a>
                <a class="btn btn-outline-info mb-4 pag-btn" href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">Last Page</a>
            </div>
        {% endif %}
    </div>
{% endblock %}